# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 881dc8b8fdd1684a305ccd9fd1c522faa78e6a179d67a12d5074dffd64cf348dd4da9a1c3f8bbf853a283fd80f8792da34145f7c689ad9a142936734183fcaee

test:
  secret_key_base: 826219a58969df11edd6f0f9ec85cff66945a659cd04d506f65550970eb0fbf35eaa3c5ff0f40bc8c0865278c6aba6186be92b96bf1e413a99b86aa2c741ac02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
